quarkus.http.port=8080

# JSON-B
quarkus.jsonb.date-format=yyyy-MM-dd

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.schema-generation.enabled=true


ratelimiter.capacity=150
ratelimiter.refillPeriodMinutes=5

quarkus.arc.remove-unused-beans=false


# Logging Configuration
quarkus.log.level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss,SSS} [%thread] %-5level %logger{36} - %msg%n
quarkus.log.file.enable=true
quarkus.log.file.path=logs/random-data.log
quarkus.log.category."com.random.data".level=DEBUG
quarkus.log.category."io.smallrye.mutiny".level=DEBUG
quarkus.log.category."java.lang.Thread".level=DEBUG
